# Generated by Django 3.2.12 on 2022-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0003_alter_waiting_wait_visit_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiting',
            options={'ordering': ['-wait_date']},
        ),
        migrations.AddField(
            model_name='waiting',
            name='wait_cancel',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='wait_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='wait_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
