# Generated by Django 3.2.12 on 2022-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0004_auto_20220330_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='wait_cancel',
            field=models.CharField(choices=[('0', '취소아님'), ('1', '취소됨')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='wait_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='wait_visit_status',
            field=models.CharField(choices=[('0', '대기 중'), ('1', '입장'), ('2', '미입장')], default='0', max_length=1),
        ),
    ]
