# Generated by Django 3.2.12 on 2022-03-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20220321_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='qna_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='qna_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='qna_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='qna_registered_date',
            new_name='registered_date',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='qna_title',
            new_name='title',
        ),
    ]
