# Generated by Django 3.2.12 on 2022-02-10 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='한글만 입력해주세요', regex='^[ㄱ-힣]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='영문/숫자를 혼합하여 입력해주세요', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=60, validators=[django.core.validators.RegexValidator(message='한글만 입력해주세요', regex='^[ㄱ-힣]*$')]),
        ),
    ]
