# Generated by Django 3.2.12 on 2022-04-14 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(db_index=True, help_text='입력 예) 01011112222', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{2,4}\\d{3,4}\\d{4}$', message='전화번호를 입력해 주세요.')]),
        ),
    ]
