# Generated by Django 3.2.12 on 2022-02-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='shop_num',
            new_name='shop_id',
        ),
    ]
