# Generated by Django 3.2.12 on 2022-02-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
