# Generated by Django 3.2.12 on 2022-02-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='shop',
            name='long',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
