# Generated by Django 3.2.12 on 2022-03-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220318_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='wait_state',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
