# Generated by Django 3.2.12 on 2022-03-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220216_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='long',
            new_name='longitude',
        ),
    ]
