# Generated by Django 3.2.12 on 2022-02-11 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220210_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='shop_num',
            new_name='shop_id',
        ),
        migrations.RemoveField(
            model_name='conv',
            name='shop_num',
        ),
        migrations.AddField(
            model_name='conv',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_convs', to='shop.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shop',
            name='long',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
    ]
