# Generated by Django 3.2.12 on 2022-02-11 13:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220211_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conv',
            name='shop_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_convs', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_num',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='숫자만 입력해주세요', regex='^[0-9]*$')]),
        ),
    ]
