# Generated by Django 3.2.12 on 2022-03-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_wait_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
