# Generated by Django 3.2.12 on 2022-04-14 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220331_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='telephone',
            field=models.CharField(help_text='입력 예) 0421112222', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{2,4}\\d{3,4}\\d{4}$', message='전화번호를 입력해 주세요.')]),
        ),
    ]
