# Generated by Django 3.2.12 on 2022-02-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_conv_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='conv_pack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='conv_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='conv_pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='conv_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Conv',
        ),
    ]
