# Generated by Django 3.2.12 on 2022-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_conv_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='shop',
            name='long',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
    ]
