# Generated by Django 3.2.9 on 2022-03-29 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='black',
            name='black_date',
        ),
        migrations.AddField(
            model_name='black',
            name='black_count',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='black',
            name='end_date',
            field=models.DateField(default=user.models.default_end_date),
        ),
        migrations.AddField(
            model_name='black',
            name='start_date',
            field=models.DateField(default=user.models.default_date),
        ),
        migrations.AddField(
            model_name='black',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
