# Generated by Django 3.2.12 on 2022-04-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blacklog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='black',
            options={'ordering': ['-black_count']},
        ),
    ]
